In [22]:
import pandas as pd
in_path="第一节代码导出的数据.csv"
all_factor=pd.read_csv(in_path)
del all_factor["Unnamed: 0"]
del all_factor["1M"]
del all_factor["3M"]
del all_factor["5M"]
del all_factor["10M"]
del all_factor["close"]
all_factor.head()

         time          ...           circulating_market_cap
0  2025-01-02          ...                         1.731194
1  2025-01-02          ...                        -0.693255
2  2025-01-02          ...                         0.706712
3  2025-01-02          ...                        -0.350280
4  2025-01-02          ...                        -1.021096

[5 rows x 14 columns]

In [23]:
def getICSeries(factors):
    fname = factors.columns[2]
    icall= factors.groupby("time").apply(lambda x: x.corr()[fname]).reset_index()
    icall = icall.dropna().drop([fname], axis=1).set_index("time")
    return icall

In [24]:
def correlation(dataset, threshold):
    """
    剔除数据集中高相关性的冗余特征，规避多重共线性
    参数:
        dataset: pandas.DataFrame - 输入的因子数据集（每行一个样本，每列一个因子）
        threshold: float - 相关性阈值（如0.8），超过此值的因子对将被视为高度相关
    返回:
        dataset: pandas.DataFrame - 剔除高相关冗余因子后的数据集
    """
    col_corr = set()  # Set of all the names of deleted columns
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if (corr_matrix.iloc[i, j] >= threshold) and (corr_matrix.columns[j] not in col_corr):
                colname = corr_matrix.columns[i] # getting the name of column
                col_corr.add(colname)
                # print(colname, corr_matrix.columns[j])
                if colname in dataset.columns:
                    del dataset[colname] # deleting the column from the dataset
                    # print("删除特征：{}".format(colname))
    return dataset

In [25]:
ic_factor = all_factor.copy()

In [26]:
time = all_factor["time"].unique()
count = 0
all_ret = []
all_t = []
all_select_factor = pd.DataFrame()

while True:
    if count>len(time)-31:
        break
    split_data = ic_factor[(ic_factor["time"]<time[29+count])&(ic_factor["time"]>=time[count])]
    icall = getICSeries(split_data)

    sort_ic = pd.DataFrame(abs(icall.mean()))
    sort_ic = sort_ic.sort_values(by=0, ascending=False)
    sort_ic = sort_ic[sort_ic[0]>0.03]

    X = icall.copy()
    X = X[sort_ic.index]
    X = correlation(X, 0.8)

    select_factor = pd.DataFrame()
    select_factor["factor"] = [X.columns.values]
    select_factor["time"] = time[29+count]
    # select_factor["ic"] = [icall.mean()[i] for i in X.columns]
    all_select_factor = all_select_factor.append(select_factor)

    # 每个季度筛选一次
    count += 11

In [27]:
def transfer_time(x):
    # 转换为日期格式，自动加1天
    date = pd.to_datetime(x)
    next_trading_day = date + timedelta(days=1)
    # 转回字符串格式，和原代码格式一致
    return next_trading_day.strftime("%Y-%m-%d")

In [28]:
from datetime import timedelta
all_select_factor["time"] = all_select_factor["time"].apply(lambda x: transfer_time(str(x)))
all_select_factor

                                              factor        time
0  [pb_ratio, circulating_market_cap, turnover_ra...  2025-02-21
0  [pb_ratio, circulating_market_cap, net_profit_...  2025-03-08
0  [pcf_ratio, net_profit_margin, net_operate_cas...  2025-03-25
0  [circulating_market_cap, pcf_ratio, net_profit...  2025-04-10
0  [circulating_market_cap, net_operate_cash_flow...  2025-04-25
0  [net_operate_cash_flow, volume, pcf_ratio, pb_...  2025-05-15
0  [circulating_market_cap, pb_ratio, volume, pe_...  2025-05-30
0  [circulating_market_cap, inc_net_profit_year_o...  2025-06-17
0  [inc_net_profit_year_on_year, pe_ratio, circul...  2025-07-02
0  [inc_net_profit_year_on_year, ps_ratio, turnov...  2025-07-17
0  [ps_ratio, net_profit_margin, pb_ratio, turnov...  2025-08-01
0  [pb_ratio, net_operate_cash_flow, ps_ratio, ne...  2025-08-16
0  [inc_net_profit_year_on_year, net_operate_cash...  2025-09-02
0  [inc_net_profit_year_on_year, pe_ratio, turnov...  2025-09-17
0  [inc_net_profit_year_on_year, circulating_mark...  2025-10-10
0            [ps_ratio, pb_ratio, pcf_ratio, volume]  2025-10-25
0  [pe_ratio, turnover_ratio, ps_ratio, net_profi...  2025-11-11
0  [turnover_ratio, pb_ratio, circulating_market_...  2025-11-26
0  [turnover_ratio, pb_ratio, circulating_market_...  2025-12-11
0  [turnover_ratio, inc_net_profit_year_on_year, ...  2025-12-26